/**
 * "AI insights" card on the Dashboard. Renders a plain-English
 * narrative of this month's spending, generated by a local Ollama
 * model.
 *
 * Lives directly above <InsightsBar /> (the rule-based anomaly cards)
 * so users see the qualitative summary first, then the specific facts
 * underneath. Both feed off the same MTD-vs-trailing-baseline math —
 * if they ever disagree, that's a bug.
 *
 * Four render states, mapped to the backend's response shapes:
 *
 *   1. Loading        — quiet skeleton, no card chrome
 *   2. Narrative      — the rendered text (demo or live)
 *   3. Disabled       — small empty state with a one-liner about
 *                       enabling Ollama; users who don't care about
 *                       LLM features should be able to scroll past
 *                       this without noticing it
 *   4. Setup-needed   — Ollama is enabled but the daemon isn't
 *                       running OR the model isn't pulled. We surface
 *                       the backend's specific 503 detail so the user
 *                       sees actionable text instead of "something
 *                       went wrong"
 *
 * Intentionally NOT dismissable like InsightsBar's individual cards:
 * this is one card per Dashboard, not a list. If the user wants it
 * gone, they flip LLM_ENABLED off in .env.
 */
import { useEffect, useRef, useState, useCallback } from 'react'
import { Sparkles, Settings, AlertTriangle, RefreshCw } from 'lucide-react'
import { getInsightsNarrative, streamInsightsNarrative } from '../api/client'

/**
 * Format an ISO timestamp as a short, human-readable freshness label.
 * "Just now" / "5m ago" / "Today, 9:47 AM" / "May 1, 9:47 AM".
 * Kept tiny — no date-fns dep for one label.
 */
function formatGeneratedAt(iso) {
  if (!iso) return ''
  const then = new Date(iso)
  if (Number.isNaN(then.getTime())) return ''
  const now = new Date()
  const diffMs = now - then
  const diffMin = Math.round(diffMs / 60000)
  if (diffMin < 1) return 'just now'
  if (diffMin < 60) return `${diffMin}m ago`
  const sameDay = then.toDateString() === now.toDateString()
  const time = then.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })
  if (sameDay) return time
  const dateStr = then.toLocaleDateString([], { month: 'short', day: 'numeric' })
  return `${dateStr}, ${time}`
}

export default function AINarrative() {
  const [state, setState] = useState({ status: 'loading' })
  const [isRefreshing, setIsRefreshing] = useState(false)
  // Tracks the in-flight stream cancel function so we can abort if the
  // user navigates away or hits Refresh again mid-stream.
  const cancelRef = useRef(null)

  // Initial-load fetch: ALWAYS non-streaming. If yesterday's cache is
  // still warm (same calendar day), backend returns the full text
  // instantly with from_cache=true — no point streaming a string we
  // already have. Only the Refresh button triggers a fresh stream.
  const fetchNarrative = useCallback(() => {
    return getInsightsNarrative({ refresh: false })
      .then((data) => {
        if (data && data.narrative) {
          setState({
            status: 'ready',
            narrative: data.narrative,
            source: data.source,        // "ollama" | "demo"
            model: data.model,
            generatedAt: data.generated_at,
            fromCache: data.from_cache,
          })
        } else if (data && data.source === 'disabled') {
          setState({ status: 'disabled' })
        } else {
          // No cached value AND not demo/disabled — fall through to a
          // streaming refresh so the user watches the model write.
          streamRefresh()
        }
      })
      .catch((err) => {
        // 503 from the backend means Ollama is enabled but unreachable
        // OR the model isn't pulled. Backend's `detail` is already
        // user-actionable ("Run `ollama pull llama3.1:8b`") — surface it.
        setState({ status: 'setup', detail: String(err.message || err) })
      })
  }, [])

  // Streaming refresh — used for the Refresh button and for first-load
  // when the cache is empty. Bypasses the daily cache server-side.
  // Renders prose token-by-token so the user sees writing happen
  // instead of staring at a spinner.
  const streamRefresh = useCallback(() => {
    // Cancel any prior in-flight stream so re-clicking Refresh doesn't
    // interleave two streams into one paragraph.
    if (cancelRef.current) cancelRef.current()
    setIsRefreshing(true)
    // Reset to a streaming-specific status so the loading skeleton
    // doesn't flash if we were already 'ready'.
    setState((prev) => prev.status === 'ready'
      ? { ...prev, narrative: '', isStreaming: true }
      : { status: 'streaming', narrative: '' })
    let metaSnapshot = null
    let accumulated = ''
    cancelRef.current = streamInsightsNarrative({
      onMeta: (meta) => {
        metaSnapshot = meta
        // If LLM is disabled mid-stream (shouldn't happen, but be
        // defensive), surface it the same way the JSON path does.
        if (meta.source === 'disabled') {
          setState({ status: 'disabled' })
        }
      },
      onDelta: (chunk) => {
        accumulated += chunk
        setState((prev) => ({
          ...prev,
          status: 'ready',
          narrative: accumulated,
          source: metaSnapshot?.source ?? prev.source,
          model: metaSnapshot?.model ?? prev.model,
          generatedAt: metaSnapshot?.generated_at ?? prev.generatedAt,
          fromCache: false,
          isStreaming: true,
        }))
      },
      onDone: () => {
        setState((prev) => ({ ...prev, isStreaming: false }))
        setIsRefreshing(false)
        cancelRef.current = null
      },
      onError: (detail) => {
        setState({ status: 'setup', detail })
        setIsRefreshing(false)
        cancelRef.current = null
      },
    })
  }, [])

  useEffect(() => {
    fetchNarrative().catch(() => {})
    return () => {
      // Component unmounting mid-stream — abort the fetch so we don't
      // leak a reader after the React tree is gone.
      if (cancelRef.current) cancelRef.current()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  if (state.status === 'loading' || (state.status === 'streaming' && !state.narrative)) {
    // Skeleton matches the dimensions of the rendered card so the page
    // doesn't reflow when the narrative arrives. Three lines of fake
    // text at decreasing widths reads as "paragraph loading" without
    // animation.
    return (
      <div style={{
        marginBottom: 24,
        padding: '16px 18px',
        border: '1px solid var(--border-soft)',
        borderRadius: 10,
        background: 'transparent',
      }}>
        <div style={{
          height: 13, width: '40%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 14,
        }} />
        <div style={{
          height: 11, width: '92%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 8,
        }} />
        <div style={{
          height: 11, width: '85%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 8,
        }} />
        <div style={{
          height: 11, width: '70%', borderRadius: 4,
          background: 'var(--border-soft)',
        }} />
      </div>
    )
  }

  if (state.status === 'disabled') {
    // Quiet: this is opt-in. Don't shout at users who haven't asked
    // for an LLM feature.
    return (
      <div style={{
        marginBottom: 24,
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '8px 12px',
        border: '1px dashed var(--border-soft)',
        borderRadius: 8,
        color: 'var(--text-muted)',
        fontSize: 12,
      }}>
        <Settings size={14} style={{ flexShrink: 0 }} />
        <span style={{ flex: 1, lineHeight: 1.4 }}>
          AI insights are off. Set{' '}
          <code style={{
            background: 'var(--bg-elevated)',
            padding: '1px 5px', borderRadius: 3, fontSize: 11,
          }}>LLM_ENABLED=true</code>{' '}
          in <code style={{
            background: 'var(--bg-elevated)',
            padding: '1px 5px', borderRadius: 3, fontSize: 11,
          }}>backend/.env</code> after installing Ollama
          to enable plain-English narratives here.
        </span>
      </div>
    )
  }

  if (state.status === 'setup') {
    // Ollama enabled but unreachable. The backend's detail string
    // already names the fix ("Run `ollama pull llama3.1:8b`") — pass
    // it through so the user sees what to do next.
    return (
      <div style={{
        marginBottom: 24,
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
        padding: '12px 14px',
        border: '1px solid rgba(251, 146, 60, 0.3)',
        borderRadius: 8,
        background: 'rgba(251, 146, 60, 0.06)',
        fontSize: 13,
      }}>
        <AlertTriangle
          size={16}
          style={{ color: 'var(--accent-orange)', flexShrink: 0, marginTop: 2 }}
        />
        <div style={{ flex: 1, color: 'var(--text-secondary)', lineHeight: 1.45 }}>
          <div style={{ fontWeight: 500, color: 'var(--text-primary)', marginBottom: 4 }}>
            AI narrative needs setup
          </div>
          {state.detail}
        </div>
      </div>
    )
  }

  // Happy path: render the narrative.
  // Split paragraphs on \n\n and render each as a <p>. The model is
  // prompted for 2-3 short paragraphs; we don't try to parse markdown
  // because the prompt explicitly forbids it.
  const paragraphs = (state.narrative || '').split(/\n\n+/).filter(Boolean)
  const isDemo = state.source === 'demo'
  const timeLabel = formatGeneratedAt(state.generatedAt)

  return (
    <div style={{
      marginBottom: 24,
      padding: '16px 18px',
      border: '1px solid rgba(175, 169, 236, 0.3)',
      borderRadius: 10,
      background: 'rgba(175, 169, 236, 0.04)',
    }}>
      {/* Eyebrow row: brand + provenance + freshness + refresh.
          Refresh is hidden in demo mode (the canned text never changes)
          and during the in-flight refresh itself. */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
        fontSize: 11,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        fontWeight: 600,
        color: 'var(--accent-purple)',
      }}>
        <Sparkles size={14} />
        <span>AI insights</span>
        <span style={{
          color: 'var(--text-dim)',
          fontWeight: 400,
          letterSpacing: 0.4,
          textTransform: 'none',
          fontSize: 11,
        }}>
          · {isDemo ? 'demo data' : `local · ${state.model || 'ollama'}`}
          {timeLabel && (
            <>
              {' · '}
              <span title={state.generatedAt}>
                generated {timeLabel}
                {state.fromCache && ' · cached'}
              </span>
            </>
          )}
        </span>
        {!isDemo && (
          <button
            type="button"
            onClick={() => streamRefresh()}
            disabled={isRefreshing}
            title={isRefreshing ? 'Generating fresh narrative…' : 'Regenerate narrative now (e.g. after a Plaid sync)'}
            style={{
              marginLeft: 'auto',
              display: 'inline-flex',
              alignItems: 'center',
              gap: 4,
              padding: '3px 8px',
              fontSize: 10,
              letterSpacing: 0.4,
              textTransform: 'uppercase',
              fontWeight: 600,
              color: isRefreshing ? 'var(--text-dim)' : 'var(--text-muted)',
              background: 'transparent',
              border: '1px solid var(--border-soft)',
              borderRadius: 6,
              cursor: isRefreshing ? 'wait' : 'pointer',
            }}
          >
            <RefreshCw
              size={11}
              style={{
                animation: isRefreshing ? 'spin 1s linear infinite' : 'none',
              }}
            />
            {isRefreshing ? 'Refreshing' : 'Refresh'}
          </button>
        )}
      </div>
      {paragraphs.map((p, i) => (
        <p key={i} style={{
          margin: 0,
          marginBottom: i < paragraphs.length - 1 ? 10 : 0,
          fontSize: 14,
          lineHeight: 1.55,
          color: 'var(--text-secondary)',
        }}>
          {p}
          {/* Blinking caret on the last paragraph while a stream is in
              flight — visual signal that more text is coming. */}
          {state.isStreaming && i === paragraphs.length - 1 && (
            <span aria-hidden="true" style={{
              display: 'inline-block',
              width: 7, height: 14,
              marginLeft: 2,
              background: 'var(--accent-purple)',
              animation: 'blink 1s step-end infinite',
              verticalAlign: 'text-bottom',
            }} />
          )}
        </p>
      ))}
      {/* Inline keyframe so the refresh icon spins without needing a
          shared CSS module entry. Keeping it scoped here means anyone
          reading this component sees the full animation contract. */}
      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
        @keyframes blink {
          0%, 50%   { opacity: 1; }
          50.01%, 100% { opacity: 0; }
        }
      `}</style>
    </div>
  )
}
