/**
 * "AI insights" card on the Dashboard. Renders a plain-English
 * narrative of this month's spending, generated by a local Ollama
 * model.
 *
 * Lives directly above <InsightsBar /> (the rule-based anomaly cards)
 * so users see the qualitative summary first, then the specific facts
 * underneath. Both feed off the same MTD-vs-trailing-baseline math —
 * if they ever disagree, that's a bug.
 *
 * Four render states, mapped to the backend's response shapes:
 *
 *   1. Loading        — quiet skeleton, no card chrome
 *   2. Narrative      — the rendered text (demo or live)
 *   3. Disabled       — small empty state with a one-liner about
 *                       enabling Ollama; users who don't care about
 *                       LLM features should be able to scroll past
 *                       this without noticing it
 *   4. Setup-needed   — Ollama is enabled but the daemon isn't
 *                       running OR the model isn't pulled. We surface
 *                       the backend's specific 503 detail so the user
 *                       sees actionable text instead of "something
 *                       went wrong"
 *
 * Intentionally NOT dismissable like InsightsBar's individual cards:
 * this is one card per Dashboard, not a list. If the user wants it
 * gone, they flip LLM_ENABLED off in .env.
 */
import { useEffect, useState } from 'react'
import { Sparkles, Settings, AlertTriangle } from 'lucide-react'
import { getInsightsNarrative } from '../api/client'

export default function AINarrative() {
  const [state, setState] = useState({ status: 'loading' })

  useEffect(() => {
    let cancelled = false
    getInsightsNarrative()
      .then((data) => {
        if (cancelled) return
        if (data && data.narrative) {
          setState({
            status: 'ready',
            narrative: data.narrative,
            source: data.source,    // "ollama" | "demo"
            model: data.model,
          })
        } else {
          // {narrative: null, source: "disabled"} — feature off
          setState({ status: 'disabled' })
        }
      })
      .catch((err) => {
        if (cancelled) return
        // 503 from the backend means Ollama is enabled but unreachable
        // OR the model isn't pulled. Backend's `detail` is already
        // user-actionable ("Run `ollama pull llama3.1:8b`") — surface it.
        setState({ status: 'setup', detail: String(err.message || err) })
      })
    return () => { cancelled = true }
  }, [])

  if (state.status === 'loading') {
    // Skeleton matches the dimensions of the rendered card so the page
    // doesn't reflow when the narrative arrives. Three lines of fake
    // text at decreasing widths reads as "paragraph loading" without
    // animation.
    return (
      <div style={{
        marginBottom: 24,
        padding: '16px 18px',
        border: '1px solid var(--border-soft)',
        borderRadius: 10,
        background: 'transparent',
      }}>
        <div style={{
          height: 13, width: '40%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 14,
        }} />
        <div style={{
          height: 11, width: '92%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 8,
        }} />
        <div style={{
          height: 11, width: '85%', borderRadius: 4,
          background: 'var(--border-soft)', marginBottom: 8,
        }} />
        <div style={{
          height: 11, width: '70%', borderRadius: 4,
          background: 'var(--border-soft)',
        }} />
      </div>
    )
  }

  if (state.status === 'disabled') {
    // Quiet: this is opt-in. Don't shout at users who haven't asked
    // for an LLM feature.
    return (
      <div style={{
        marginBottom: 24,
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '8px 12px',
        border: '1px dashed var(--border-soft)',
        borderRadius: 8,
        color: 'var(--text-muted)',
        fontSize: 12,
      }}>
        <Settings size={14} style={{ flexShrink: 0 }} />
        <span style={{ flex: 1, lineHeight: 1.4 }}>
          AI insights are off. Set{' '}
          <code style={{
            background: 'var(--bg-elevated)',
            padding: '1px 5px', borderRadius: 3, fontSize: 11,
          }}>LLM_ENABLED=true</code>{' '}
          in <code style={{
            background: 'var(--bg-elevated)',
            padding: '1px 5px', borderRadius: 3, fontSize: 11,
          }}>backend/.env</code> after installing Ollama
          to enable plain-English narratives here.
        </span>
      </div>
    )
  }

  if (state.status === 'setup') {
    // Ollama enabled but unreachable. The backend's detail string
    // already names the fix ("Run `ollama pull llama3.1:8b`") — pass
    // it through so the user sees what to do next.
    return (
      <div style={{
        marginBottom: 24,
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
        padding: '12px 14px',
        border: '1px solid rgba(251, 146, 60, 0.3)',
        borderRadius: 8,
        background: 'rgba(251, 146, 60, 0.06)',
        fontSize: 13,
      }}>
        <AlertTriangle
          size={16}
          style={{ color: 'var(--accent-orange)', flexShrink: 0, marginTop: 2 }}
        />
        <div style={{ flex: 1, color: 'var(--text-secondary)', lineHeight: 1.45 }}>
          <div style={{ fontWeight: 500, color: 'var(--text-primary)', marginBottom: 4 }}>
            AI narrative needs setup
          </div>
          {state.detail}
        </div>
      </div>
    )
  }

  // Happy path: render the narrative.
  // Split paragraphs on \n\n and render each as a <p>. The model is
  // prompted for 2-3 short paragraphs; we don't try to parse markdown
  // because the prompt explicitly forbids it.
  const paragraphs = (state.narrative || '').split(/\n\n+/).filter(Boolean)
  const isDemo = state.source === 'demo'

  return (
    <div style={{
      marginBottom: 24,
      padding: '16px 18px',
      border: '1px solid rgba(175, 169, 236, 0.3)',
      borderRadius: 10,
      background: 'rgba(175, 169, 236, 0.04)',
    }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
        fontSize: 11,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        fontWeight: 600,
        color: 'var(--accent-purple)',
      }}>
        <Sparkles size={14} />
        <span>AI insights</span>
        <span style={{
          color: 'var(--text-dim)',
          fontWeight: 400,
          letterSpacing: 0.4,
          textTransform: 'none',
          fontSize: 11,
        }}>
          · {isDemo ? 'demo data' : `local · ${state.model || 'ollama'}`}
        </span>
      </div>
      {paragraphs.map((p, i) => (
        <p key={i} style={{
          margin: 0,
          marginBottom: i < paragraphs.length - 1 ? 10 : 0,
          fontSize: 14,
          lineHeight: 1.55,
          color: 'var(--text-secondary)',
        }}>
          {p}
        </p>
      ))}
    </div>
  )
}
