"""
Curated, pre-built prompts for the in-app "Ask" panel.

Why a fixed catalog instead of free-form chat:

  * The local LLM target is llama3.1:8b. An 8B model is fine at
    rephrasing structured numbers but it's not reliable at picking the
    right SQL/aggregation when given an arbitrary natural-language
    question. By limiting the surface to a handful of curated prompts
    we get to do the data lookup in Python (where we have tests) and
    leave the model with the much narrower job of writing prose around
    pre-computed numbers.

  * The "no hallucination" invariant from the AI Insights card carries
    over: every dollar figure in the response was computed from the DB
    in a Python handler, NOT generated by the model. The model can
    only restate numbers it was given.

Architecture mirrors `insights_narrative.py`:

  1. A handler builds a JSON "bundle" of facts for a given prompt + horizon.
  2. `build_user_prompt(prompt_id, bundle)` wraps the bundle in a
     handler-specific instruction.
  3. The router calls the OllamaClient with CHAT_SYSTEM_PROMPT + the
     user prompt and returns the model's text.

Adding a new curated prompt:
  1. Add an entry to `PROMPT_CATALOG`.
  2. Implement a `_build_<id>_bundle(db, horizon)` function below.
  3. Register the handler in `_HANDLERS`.

Demo mode: handlers run against the demo DB transparently (the router
passes the right session via get_db). Numbers will be the synthetic
Alex Carter values from seed_demo.py — that's the point.
"""
from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Callable, Optional

from sqlalchemy.orm import Session, joinedload

from sqlalchemy import func

from app.models import (
    Account,
    Budget,
    BudgetCategory,
    CreditCardDetail,
    Holding,
    MortgageDetail,
    NetWorthSnapshot,
    Transaction,
)


# ─── Shared system prompt ──────────────────────────────────────────────
#
# Same shape as insights_narrative.SYSTEM_PROMPT but tuned for
# single-question conversational answers (one short paragraph rather
# than 2-3 paragraphs). Hard rules are non-negotiable: the model only
# restates numbers it was given.
CHAT_SYSTEM_PROMPT = """You are a concise financial assistant answering
a single question in the user's personal finance dashboard. You will be
given a JSON object of pre-computed facts.

Hard rules — these are not suggestions:
  - ONLY use numbers that appear verbatim in the provided JSON. Do not
    estimate, extrapolate, or invent any dollar figures, percentages,
    counts, or dates.
  - Do not give financial advice. Do not warn about budgeting. Do not
    recommend categories to cut, accounts to open, or trades to make.
    Just answer the question with the facts you were given.
  - 1 to 3 short sentences. Plain English, no bullet lists, no
    markdown, no headings, no sign-off.
  - Refer to the user as "you".
  - The JSON's "horizon_label" tells you what time window the numbers
    cover. Use that label naturally in the answer (e.g. "over the past
    week", "today").
  - If the JSON contains a `comparison` field, mention the change vs
    that comparison ONCE, briefly. If `comparison` is null, don't
    speculate about trends.
  - If the JSON has no meaningful data (e.g. empty list, zero total,
    "no_data": true), say so plainly in one sentence — don't pad.

Answer the user's question directly. Open with the headline number.
"""


# ─── Catalog ───────────────────────────────────────────────────────────
#
# What the frontend gets from GET /api/chat/prompts. Stable shape; the
# UI uses `id` to POST back to /api/chat/answer.
#
# Horizon ids are strings (not enums) because the frontend renders them
# as chips; whatever the user picks comes back to the handler as-is.

@dataclass
class PromptHorizon:
    id: str            # "1d" | "1w" | "1mo" | "1yr" | "today" | "7d" | "30d"
    label: str         # short label shown in the UI chip

    def to_dict(self) -> dict:
        return {"id": self.id, "label": self.label}


@dataclass
class PromptDef:
    id: str
    label: str          # the question itself, e.g. "How much have I spent"
    description: str    # subtle one-liner shown under the question chip
    horizons: list[PromptHorizon]

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "label": self.label,
            "description": self.description,
            "horizons": [h.to_dict() for h in self.horizons],
        }


# Horizon presets reused across multiple prompts.
_SPENDING_HORIZONS = [
    PromptHorizon("today", "Today"),
    PromptHorizon("1w", "Past week"),
    PromptHorizon("1mo", "Past month"),
    PromptHorizon("1yr", "Past year"),
]

_NET_WORTH_HORIZONS = [
    PromptHorizon("1d", "Today"),
    PromptHorizon("1w", "1 week"),
    PromptHorizon("1mo", "1 month"),
    PromptHorizon("1yr", "1 year"),
]

_BILLS_HORIZONS = [
    PromptHorizon("7d", "Next 7 days"),
    PromptHorizon("30d", "Next 30 days"),
]

# Prompts that look at backward-looking flows but don't make sense for a
# single-day window (e.g. "income today" is rarely useful — paychecks
# don't land daily). Skip the today/1d horizon for these.
_FLOW_HORIZONS = [
    PromptHorizon("1w", "Past week"),
    PromptHorizon("1mo", "Past month"),
    PromptHorizon("1yr", "Past year"),
]

# "There is one right answer right now" — used by prompts that compute a
# single point-in-time value with no time-window axis (current-month
# overspend, accounts that are stale RIGHT NOW, trailing-90 savings
# rate). The chip is just there so the UI's selector logic doesn't
# special-case zero-horizon prompts.
_NOW_HORIZON = [PromptHorizon("now", "Right now")]


PROMPT_CATALOG: list[PromptDef] = [
    PromptDef(
        id="spending_total",
        label="How much have I spent",
        description="Total spending and top categories for a window",
        horizons=_SPENDING_HORIZONS,
    ),
    PromptDef(
        id="net_worth_change",
        label="What changed in my net worth",
        description="Net worth now vs the start of the window",
        horizons=_NET_WORTH_HORIZONS,
    ),
    PromptDef(
        id="upcoming_bills",
        label="What bills are coming up",
        description="Mortgage and credit card payments due soon",
        horizons=_BILLS_HORIZONS,
    ),
    PromptDef(
        id="portfolio_status",
        label="How's my portfolio doing",
        description="Total value, gain/loss, and recent change",
        horizons=_SPENDING_HORIZONS,
    ),
    PromptDef(
        id="overspending",
        label="Where am I overspending",
        description="Budget categories above their limit this month",
        horizons=_NOW_HORIZON,
    ),
    PromptDef(
        id="top_merchants",
        label="Who am I spending the most with",
        description="Top merchants by total spend in a window",
        horizons=_FLOW_HORIZONS,
    ),
    PromptDef(
        id="income_total",
        label="How much income did I receive",
        description="Sum of inflows hitting bank accounts",
        horizons=_FLOW_HORIZONS,
    ),
    PromptDef(
        id="stale_accounts",
        label="Are any accounts overdue for an update",
        description="Plaid syncs that have stopped or manual statements past due",
        horizons=_NOW_HORIZON,
    ),
    PromptDef(
        id="savings_rate",
        label="What's my savings rate",
        description="Bank-visible savings rate over the last 90 days",
        horizons=_NOW_HORIZON,
    ),
]


def get_catalog() -> list[dict]:
    """Serialised catalog for GET /api/chat/prompts."""
    return [p.to_dict() for p in PROMPT_CATALOG]


# ─── Horizon → date helpers ────────────────────────────────────────────

def _horizon_window(horizon: str, today: Optional[date] = None) -> tuple[date, date, str]:
    """Resolve a horizon id to (start_date, end_date, label).

    Both ends are inclusive. Labels are written for the LLM to drop into
    its sentence verbatim, so they stay grammatical ("over the past week").
    """
    today = today or date.today()
    if horizon == "today" or horizon == "1d":
        return today, today, "today"
    if horizon == "1w" or horizon == "7d":
        return today - timedelta(days=6), today, "over the past 7 days"
    if horizon == "1mo" or horizon == "30d":
        return today - timedelta(days=29), today, "over the past 30 days"
    if horizon == "1yr":
        return today - timedelta(days=364), today, "over the past 12 months"
    if horizon == "now":
        return today, today, "right now"
    raise ValueError(f"Unknown horizon: {horizon!r}")


def _horizon_days(horizon: str) -> int:
    """Number of days the horizon covers (used for prior-period comparisons)."""
    return {
        "today": 1, "1d": 1,
        "1w": 7, "7d": 7,
        "1mo": 30, "30d": 30,
        "1yr": 365,
        "now": 0,
    }[horizon]


# ─── Handler: spending_total ───────────────────────────────────────────

def _build_spending_total_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Total spending in the window + top 3 categories + prior-period delta."""
    today = today or date.today()
    start, end, label = _horizon_window(horizon, today=today)
    days = _horizon_days(horizon)

    # Period spending (positive = money out, exclude transfers).
    period_txns = db.query(Transaction).filter(
        Transaction.date >= start,
        Transaction.date <= end,
        Transaction.amount > 0,
        Transaction.is_transfer.is_(False),
    ).all()

    by_cat: dict[str, float] = defaultdict(float)
    for t in period_txns:
        cat = t.custom_category or t.category or "Uncategorized"
        by_cat[cat] += t.amount
    total = round(sum(by_cat.values()), 2)
    top_cats = sorted(by_cat.items(), key=lambda kv: kv[1], reverse=True)[:3]

    # Prior period of the same length (no comparison for "today" — too noisy).
    comparison: Optional[dict] = None
    if horizon != "today" and horizon != "1d":
        prior_end = start - timedelta(days=1)
        prior_start = prior_end - timedelta(days=days - 1)
        prior_total = (
            db.query(Transaction)
            .filter(
                Transaction.date >= prior_start,
                Transaction.date <= prior_end,
                Transaction.amount > 0,
                Transaction.is_transfer.is_(False),
            )
            .with_entities(Transaction.amount)
            .all()
        )
        prior_sum = round(sum(a for (a,) in prior_total), 2)
        delta = round(total - prior_sum, 2)
        pct = round(((total / prior_sum) - 1) * 100, 1) if prior_sum > 0 else None
        # If the prior period had nothing in it (no synced data that far
        # back), the delta is meaningless — the model would otherwise
        # claim "spending up $X over the prior period" when really no
        # prior data exists. Mark it so the LLM can skip the comparison.
        prior_unreliable = prior_sum == 0
        comparison = {
            "prior_period_label": f"prior {days} days",
            "prior_period_start": prior_start.isoformat(),
            "prior_period_end": prior_end.isoformat(),
            "prior_total_dollars": prior_sum,
            "change_dollars": delta,
            "change_percent": pct,
            "prior_period_unreliable": prior_unreliable,
            "prior_unreliable_reason": (
                "Prior period total is $0 — no synced transactions exist "
                "that far back. Ignore the change_dollars value; describe "
                "current-period spending only."
            ) if prior_unreliable else None,
        }

    return {
        "horizon_label": label,
        "horizon_days": days,
        "period_start": start.isoformat(),
        "period_end": end.isoformat(),
        "transaction_count": len(period_txns),
        "total_spent_dollars": total,
        "top_categories": [
            {"category": cat, "amount_dollars": round(amt, 2)}
            for cat, amt in top_cats
        ],
        "comparison": comparison,
        "no_data": len(period_txns) == 0,
    }


# ─── Handler: net_worth_change ─────────────────────────────────────────

def _build_net_worth_change_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Latest net worth + the snapshot from `horizon` ago + delta."""
    today = today or date.today()
    days = _horizon_days(horizon)
    horizon_start = today - timedelta(days=days)

    latest = (
        db.query(NetWorthSnapshot)
        .order_by(NetWorthSnapshot.date.desc())
        .first()
    )
    if latest is None:
        return {
            "horizon_label": _horizon_window(horizon, today=today)[2],
            "no_data": True,
            "reason": "no_net_worth_snapshots",
        }

    # Find the snapshot closest to (but not after) horizon_start. SQLite
    # doesn't have a tidy "snap to nearest" so we just query <= and order
    # desc to pick the most recent one before the cutoff.
    baseline = (
        db.query(NetWorthSnapshot)
        .filter(NetWorthSnapshot.date <= horizon_start)
        .order_by(NetWorthSnapshot.date.desc())
        .first()
    )
    # Fallback: oldest snapshot we have, in case the user has fewer days
    # of history than the horizon.
    if baseline is None:
        baseline = (
            db.query(NetWorthSnapshot)
            .order_by(NetWorthSnapshot.date.asc())
            .first()
        )

    latest_total = round(float(latest.net_worth or 0), 2)
    # Bug fix: NetWorthSnapshot's column is `net_worth`, not
    # `total_net_worth` — the earlier name caused a 500 every time this
    # handler ran. Keeping a canary comment so the rename doesn't sneak
    # back in via copy-paste.
    baseline_total_raw = round(float(baseline.net_worth or 0), 2)

    # Common-account math (mirrors the Net Worth page's RecentMovementStrip):
    # raw net_worth is the sum of WHATEVER accounts existed on each
    # snapshot day. New accounts onboarded between baseline and latest
    # would otherwise show up as "growth" — but it's not growth, it's
    # an account that's now visible. Tusk Ledger's first week of use
    # is exactly when this happens, so the bug surfaces immediately.
    # Compute the delta on the intersection of account ids present in
    # BOTH snapshots; surface accounts_added so the LLM can mention it.
    lb = latest.account_balances or {}
    bb = baseline.account_balances or {}
    accounts_added = 0
    common_baseline_total = baseline_total_raw
    common_latest_total = latest_total
    using_common_set = False
    if lb and bb:
        baseline_ids = set(bb.keys())
        latest_ids = set(lb.keys())
        common = baseline_ids & latest_ids
        if common:
            common_baseline_total = round(sum(float(bb[i] or 0) for i in common), 2)
            common_latest_total = round(sum(float(lb[i] or 0) for i in common), 2)
            accounts_added = len(latest_ids - baseline_ids)
            using_common_set = True

    delta = round(common_latest_total - common_baseline_total, 2)
    pct = (
        round((delta / abs(common_baseline_total)) * 100, 1)
        if common_baseline_total else None
    )

    # Was the baseline truncated to the oldest snapshot we have because
    # the user lacks history that goes back `days` days? When this is
    # true, "$X over the past month" would be misleading — we actually
    # only have N days of history. Surface the truncation in the
    # bundle so the LLM (and the templated fallback) say "since the
    # earliest snapshot on YYYY-MM-DD" instead.
    actual_window_days = (latest.date - baseline.date).days
    baseline_truncated = baseline.date > horizon_start

    if baseline_truncated:
        horizon_label = (
            f"since the earliest snapshot we have ({baseline.date.isoformat()})"
        )
    else:
        horizon_label = _horizon_window(horizon, today=today)[2]

    return {
        "horizon_label": horizon_label,
        "requested_horizon_days": days,
        "actual_window_days": actual_window_days,
        "baseline_truncated": baseline_truncated,
        "latest_net_worth_dollars": latest_total,
        "latest_snapshot_date": latest.date.isoformat(),
        "baseline_net_worth_dollars": baseline_total_raw,
        "baseline_snapshot_date": baseline.date.isoformat(),
        # Apples-to-apples delta on the common account set. This is
        # what the model should restate when discussing change.
        "common_baseline_total_dollars": common_baseline_total,
        "common_latest_total_dollars": common_latest_total,
        "change_dollars": delta,
        "change_percent": pct,
        "accounts_added_since_baseline": accounts_added,
        "delta_methodology": (
            "Computed on the INTERSECTION of accounts present in both "
            "snapshots. Newly onboarded accounts are excluded from the "
            "delta so they don't masquerade as growth. If "
            "accounts_added_since_baseline > 0, mention briefly that "
            "more accounts are now being tracked."
        ) if using_common_set else (
            "Raw net_worth diff (one or both snapshots lacks per-account "
            "JSON). May include accounts that didn't exist in the baseline."
        ),
        "latest_assets_dollars": round(float(latest.total_assets or 0), 2),
        "latest_liabilities_dollars": round(float(latest.total_liabilities or 0), 2),
        "no_data": False,
    }


# ─── Handler: upcoming_bills ───────────────────────────────────────────

def _build_upcoming_bills_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Mortgage + credit card payments due in the window."""
    today = today or date.today()
    days = _horizon_days(horizon)
    cutoff = today + timedelta(days=days)
    label = "in the next 7 days" if horizon == "7d" else "in the next 30 days"

    bills: list[dict] = []

    # Mortgages (next_monthly_payment)
    mortgages = (
        db.query(MortgageDetail)
        .options(joinedload(MortgageDetail.account))
        .filter(MortgageDetail.next_payment_due_date.isnot(None))
        .all()
    )
    for m in mortgages:
        d = m.next_payment_due_date
        if d > cutoff or d < today:
            continue
        acct = m.account
        bills.append({
            "kind": "mortgage",
            "account": (acct.custom_name or acct.name) if acct else "(unknown)",
            "due_date": d.isoformat(),
            "days_until": (d - today).days,
            "amount_dollars": round(float(m.next_monthly_payment or 0), 2),
        })

    # Credit cards (last_statement_balance)
    cards = (
        db.query(CreditCardDetail)
        .options(joinedload(CreditCardDetail.account))
        .filter(CreditCardDetail.next_payment_due_date.isnot(None))
        .all()
    )
    for c in cards:
        d = c.next_payment_due_date
        if d > cutoff or d < today:
            continue
        acct = c.account
        bills.append({
            "kind": "credit_card",
            "account": (acct.custom_name or acct.name) if acct else "(unknown)",
            "due_date": d.isoformat(),
            "days_until": (d - today).days,
            "amount_dollars": round(float(c.last_statement_balance or 0), 2),
            "minimum_dollars": round(float(c.minimum_payment_amount or 0), 2),
        })

    bills.sort(key=lambda b: b["due_date"])
    total = round(sum(b["amount_dollars"] for b in bills), 2)

    return {
        "horizon_label": label,
        "horizon_days": days,
        "bill_count": len(bills),
        "total_due_dollars": total,
        "bills": bills,
        "no_data": len(bills) == 0,
        # Scope is intentionally narrow: only mortgages and credit cards
        # with structured Plaid liabilities data are surfaced. Manual
        # liabilities (Apple Card, student loans, auto) and Plaid items
        # without a populated next_payment_due_date are excluded — the
        # data source is too sparse to be reliable for them. Mention
        # this in the answer so the user understands why a known bill
        # might be missing.
        "scope_note": (
            "Only mortgage and credit-card payments with a populated "
            "next_payment_due_date from Plaid are included. Manual "
            "liabilities (e.g., Apple Card, student loans, auto loans) "
            "and Plaid accounts that don't expose this field will not "
            "appear here even if a payment is due."
        ),
    }


# ─── Handler: portfolio_status ─────────────────────────────────────────

def _build_portfolio_status_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Total portfolio value + unrealized gain/loss + change vs horizon."""
    today = today or date.today()
    days = _horizon_days(horizon)
    label = _horizon_window(horizon, today=today)[2]

    holdings = (
        db.query(Holding)
        .options(joinedload(Holding.security), joinedload(Holding.account))
        .all()
    )

    # Track three things separately, mirroring /api/investments/summary
    # so the numbers in the Ask answer match the Investments page:
    #
    #   total_value     = everything (cash + invested + manual accounts)
    #   total_invested  = non-cash holdings only — denominator for gain/loss
    #   total_cost      = cost basis of non-cash holdings (where known)
    #
    # Earlier version computed gain_loss as (total_value - total_cost).
    # That's apples-to-oranges: total_value includes the cash sleeve
    # (e.g. ~$123k of "U S Dollar" in a Robinhood account) AND any
    # manual-account balances that have no cost basis recorded, while
    # total_cost only sums cost basis from non-cash holdings. Result was
    # absurd numbers like "+181% unrealized gain" on this user's data.
    # Compute against total_invested instead so the math is honest.
    total_value = 0.0
    total_invested = 0.0
    total_cost = 0.0
    cost_known = False
    holdings_data: list[tuple[float, str | None, str | None, bool]] = []
    for h in holdings:
        value = float(h.institution_value or 0.0)
        total_value += value
        is_cash = bool(h.security and h.security.is_cash_equivalent)
        if not is_cash:
            total_invested += value
            if h.cost_basis is not None:
                total_cost += float(h.cost_basis)
                cost_known = True
        ticker = h.security.ticker_symbol if h.security else None
        sec_name = h.security.name if h.security else None
        holdings_data.append((value, sec_name, ticker, is_cash))

    # Pull in manual investment accounts (HSA, 403b, etc.) the same way
    # /api/investments/summary does — otherwise the total is short by
    # whatever balance the user keeps in non-Plaid investment accounts.
    # These have no Holdings rows, so we can't split cash-vs-invested;
    # treat the whole balance as 'invested' to stay consistent with the
    # Investments page (its comment notes the same caveat).
    plaid_holding_account_ids = {h.account_id for h in holdings if h.account_id}
    manual_invest = (
        db.query(Account)
        .filter(Account.type == "investment")
        .all()
    )
    for acct in manual_invest:
        if acct.id in plaid_holding_account_ids:
            continue
        bal = float(acct.current_balance or 0.0)
        if bal <= 0:
            continue
        total_value += bal
        total_invested += bal
        holdings_data.append((bal, acct.custom_name or acct.name, None, False))

    total_value = round(total_value, 2)
    total_invested = round(total_invested, 2)
    total_cost = round(total_cost, 2) if cost_known else None
    # Gain/loss is invested-minus-cost (NOT value-minus-cost). For users
    # whose entire portfolio has known cost basis these match; for users
    # with cash sleeves or manual accounts they diverge significantly.
    gain_loss = round(total_invested - total_cost, 2) if cost_known else None
    gain_loss_pct = (
        round((gain_loss / total_cost) * 100, 1)
        if cost_known and total_cost
        else None
    )

    # Top 3 holdings — exclude cash equivalents so "U S Dollar" doesn't
    # show up as the user's #2 "holding" (true but not what they mean
    # when they ask 'how is my portfolio doing').
    top = sorted(
        [h for h in holdings_data if not h[3]],
        key=lambda x: x[0],
        reverse=True,
    )[:3]
    top_holdings = [
        {
            "label": ticker or sec_name or "(unnamed)",
            "value_dollars": round(value, 2),
        }
        for value, sec_name, ticker, _is_cash in top
        if value > 0
    ]

    # Net-worth-derived comparison: investments are part of net worth, so
    # the simplest honest "how has the portfolio moved" signal is the
    # delta between today's snapshot's investment-component and the
    # snapshot from horizon days ago. NetWorthSnapshot stores total_assets
    # but not a per-bucket investment number, so we approximate by using
    # the change in total assets — labelled as such so the model doesn't
    # claim it's only the portfolio. For "today" we skip the comparison.
    # Comparison: deliberately strict here — only emit when we actually
    # have a snapshot from at-or-before the requested horizon. Falling
    # back to the oldest snapshot (the way net_worth_change does) would
    # silently report a 7-day delta as if it were a 1-year delta.
    #
    # Same common-account caveat as net_worth_change: compute the delta
    # on the intersection of account ids present in BOTH snapshots so a
    # newly onboarded $200k 401(k) doesn't show up as portfolio gain.
    comparison: Optional[dict] = None
    if horizon not in ("today", "1d"):
        latest = (
            db.query(NetWorthSnapshot).order_by(NetWorthSnapshot.date.desc()).first()
        )
        horizon_start = today - timedelta(days=days)
        baseline = (
            db.query(NetWorthSnapshot)
            .filter(NetWorthSnapshot.date <= horizon_start)
            .order_by(NetWorthSnapshot.date.desc())
            .first()
        )
        if latest is not None and baseline is not None:
            la_raw = float(latest.total_assets or 0)
            ba_raw = float(baseline.total_assets or 0)
            lb = latest.account_balances or {}
            bb = baseline.account_balances or {}
            la = la_raw
            ba = ba_raw
            accounts_added = 0
            using_common_set = False
            if lb and bb:
                common = set(lb.keys()) & set(bb.keys())
                if common:
                    # Account_balances is signed (assets positive,
                    # liabilities negative). Filter to positives only so
                    # this stays an "assets" metric, parallel to
                    # total_assets above.
                    la = round(sum(max(float(lb[i] or 0), 0) for i in common), 2)
                    ba = round(sum(max(float(bb[i] or 0), 0) for i in common), 2)
                    accounts_added = len(set(lb.keys()) - set(bb.keys()))
                    using_common_set = True
            delta = round(la - ba, 2)
            pct = round((delta / ba) * 100, 1) if ba else None
            comparison = {
                "metric": "total_assets_common_accounts" if using_common_set else "total_assets",
                "note": (
                    "Change in total ASSETS (not just investments) between "
                    "snapshots, computed on the intersection of accounts "
                    "present in both. Mention briefly that this is an "
                    "assets proxy, not pure portfolio."
                ) if using_common_set else (
                    "Approximate proxy for portfolio change: change in "
                    "total ASSETS (not just investments) between snapshots. "
                    "Per-account breakdown was unavailable, so newly added "
                    "accounts may inflate the delta."
                ),
                "baseline_date": baseline.date.isoformat(),
                "baseline_total_assets_dollars": round(ba, 2),
                "latest_total_assets_dollars": round(la, 2),
                "change_dollars": delta,
                "change_percent": pct,
                "accounts_added_since_baseline": accounts_added,
            }
        elif latest is not None and baseline is None:
            # Honest absence — tell the LLM why there's no comparison.
            comparison = {
                "unavailable": True,
                "reason": (
                    f"No net worth snapshot exists from on or before "
                    f"{horizon_start.isoformat()}. Don't claim a "
                    f"comparison; just describe the current portfolio."
                ),
            }

    return {
        "horizon_label": label,
        "horizon_days": days,
        "total_portfolio_value_dollars": total_value,
        "total_invested_value_dollars": total_invested,
        "total_cost_basis_dollars": total_cost,
        "unrealized_gain_loss_dollars": gain_loss,
        "unrealized_gain_loss_percent": gain_loss_pct,
        "gain_loss_definition": (
            "unrealized_gain_loss_dollars = total_invested_value_dollars "
            "(non-cash holdings + manual investment account balances) "
            "MINUS total_cost_basis_dollars. It does NOT use "
            "total_portfolio_value_dollars (which includes cash sleeves)."
        ),
        "top_holdings": top_holdings,
        "comparison": comparison,
        "no_data": total_value == 0,
    }


# ─── Handler: overspending ─────────────────────────────────────────────

def _build_overspending_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Categories that have already crossed (or are pacing past) their
    monthly budget limit. Mirrors what the Budgets page shows.

    Compares MTD spending in each budgeted category against that
    category's `limit_amount` for the current month's Budget. We don't
    pace-adjust here on purpose — "you're at 90% on day 15" is a useful
    signal regardless of whether we'd extrapolate to "on track to spend
    180%". The model gets `days_into_month` and `days_in_month` so it
    can mention pacing if relevant.

    No budget for the current month → no_data: true with a note
    explaining the user hasn't set up a budget for this month yet.
    """
    today = today or date.today()
    month_start = today.replace(day=1)
    if today.month == 12:
        next_month_start = date(today.year + 1, 1, 1)
    else:
        next_month_start = date(today.year, today.month + 1, 1)
    days_in_month = (next_month_start - month_start).days
    days_elapsed = (today - month_start).days + 1

    budget = (
        db.query(Budget)
        .filter(Budget.year == today.year, Budget.month == today.month)
        .first()
    )
    if not budget or not budget.categories:
        return {
            "horizon_label": today.strftime("%B %Y"),
            "no_data": True,
            "reason": (
                f"No budget configured for {today.strftime('%B %Y')}. "
                f"Set one up on the Budgets page to enable this answer."
            ),
        }

    # MTD spending per category — exclude transfers, count positives only.
    mtd_rows = (
        db.query(Transaction)
        .filter(
            Transaction.date >= month_start,
            Transaction.date <= today,
            Transaction.amount > 0,
            Transaction.is_transfer.is_(False),
        )
        .all()
    )
    by_cat: dict[str, float] = defaultdict(float)
    for t in mtd_rows:
        cat = t.custom_category or t.category or "Uncategorized"
        by_cat[cat] += t.amount

    rows = []
    for bc in budget.categories:
        # Skip the synthetic "Business" rollup category — it's tracked
        # separately on the Budgets page and isn't a real spending bucket.
        if bc.category == "Business":
            continue
        spent = round(by_cat.get(bc.category, 0.0), 2)
        limit = round(float(bc.limit_amount), 2)
        if limit <= 0:
            continue
        pct = round((spent / limit) * 100, 1)
        rows.append({
            "category": bc.category,
            "spent_dollars": spent,
            "limit_dollars": limit,
            "percent_used": pct,
            "over_dollars": round(max(spent - limit, 0), 2),
            "is_over": spent > limit,
        })

    over = sorted(
        [r for r in rows if r["is_over"]],
        key=lambda r: r["over_dollars"], reverse=True,
    )
    near_cap = sorted(
        [r for r in rows if not r["is_over"] and r["percent_used"] >= 80],
        key=lambda r: r["percent_used"], reverse=True,
    )

    # no_data is reserved for "we can't answer" (no budget exists). When
    # a budget IS set but nothing's over and nothing's near cap, that's
    # a real, useful answer — set `nothing_to_flag` instead so the LLM
    # and templated fallback can say "you're on track" rather than "no
    # data".
    return {
        "horizon_label": today.strftime("%B %Y"),
        "days_into_month": days_elapsed,
        "days_in_month": days_in_month,
        "budget_categories_count": sum(1 for bc in budget.categories if bc.category != "Business"),
        "categories_over_budget": over,
        "categories_near_cap": near_cap,
        "categories_over_count": len(over),
        "categories_near_cap_count": len(near_cap),
        "total_over_dollars": round(sum(r["over_dollars"] for r in over), 2),
        "nothing_to_flag": len(over) == 0 and len(near_cap) == 0,
        "no_data": False,
    }


# ─── Handler: top_merchants ────────────────────────────────────────────

def _build_top_merchants_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Top 5 merchants by total spend in the window."""
    today = today or date.today()
    start, end, label = _horizon_window(horizon, today=today)
    txns = (
        db.query(Transaction)
        .filter(
            Transaction.date >= start,
            Transaction.date <= end,
            Transaction.amount > 0,
            Transaction.is_transfer.is_(False),
        )
        .all()
    )
    by_merch: dict[str, dict] = {}
    for t in txns:
        # Use merchant_name when available, fall back to name. Skip
        # display_name normalization here — it requires importing the
        # merchant_normalizer service which has its own non-trivial
        # path. Raw merchant_name is what other parts of the app key on.
        m = (t.merchant_name or t.name or "Unknown").strip()
        b = by_merch.setdefault(m, {"merchant": m, "total": 0.0, "count": 0})
        b["total"] += t.amount
        b["count"] += 1
    top = sorted(by_merch.values(), key=lambda x: x["total"], reverse=True)[:5]
    overall_total = round(sum(x["total"] for x in by_merch.values()), 2)
    return {
        "horizon_label": label,
        "horizon_days": _horizon_days(horizon),
        "period_start": start.isoformat(),
        "period_end": end.isoformat(),
        "merchant_count": len(by_merch),
        "total_spending_dollars": overall_total,
        "top_merchants": [
            {
                "merchant": x["merchant"],
                "total_dollars": round(x["total"], 2),
                "transaction_count": x["count"],
                "share_of_total_pct": round((x["total"] / overall_total) * 100, 1) if overall_total else None,
            }
            for x in top
        ],
        "no_data": len(by_merch) == 0,
    }


# ─── Handler: income_total ─────────────────────────────────────────────

def _build_income_total_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Sum of inflows hitting bank accounts in the window.

    Plaid convention: amount<0 = money in. We exclude transfers (CC
    payoffs etc.) so the number reflects ACTUAL income, not money
    moving between the user's own accounts. Also surface the top 3
    inflow sources for color.

    Caveat the LLM should mention: 401(k)/403(b) payroll deferrals are
    invisible to Plaid because they never hit a bank account. So this
    is a FLOOR, not the user's full gross.
    """
    today = today or date.today()
    start, end, label = _horizon_window(horizon, today=today)
    txns = (
        db.query(Transaction)
        .filter(
            Transaction.date >= start,
            Transaction.date <= end,
            Transaction.amount < 0,
            Transaction.is_transfer.is_(False),
        )
        .all()
    )
    by_src: dict[str, float] = defaultdict(float)
    total = 0.0
    for t in txns:
        amt = -float(t.amount)  # flip sign so income reads positive
        total += amt
        m = (t.merchant_name or t.name or "Unknown").strip()
        by_src[m] += amt
    top_sources = sorted(by_src.items(), key=lambda kv: kv[1], reverse=True)[:3]
    return {
        "horizon_label": label,
        "horizon_days": _horizon_days(horizon),
        "period_start": start.isoformat(),
        "period_end": end.isoformat(),
        "deposit_count": len(txns),
        "total_income_dollars": round(total, 2),
        "top_sources": [
            {"source": src, "amount_dollars": round(amt, 2)}
            for src, amt in top_sources
        ],
        "scope_note": (
            "Income here is what hit your bank accounts (Plaid-visible "
            "deposits). 401(k)/403(b) payroll deferrals are NOT included "
            "because they never traverse a bank account — so this is a "
            "floor on gross income, not the full picture."
        ),
        "no_data": len(txns) == 0,
    }


# ─── Handler: stale_accounts ───────────────────────────────────────────

# Same thresholds the /api/accounts/stale endpoint uses. Keep them in
# sync — if the dashboard bell starts using a different number, this
# answer will look out of step with what users see in the sidebar.
_PLAID_STALE_DAYS = 7


def _build_stale_accounts_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Accounts that are overdue for an update.

    Two cadences (mirrors routers/accounts.py /stale):
      - Plaid accounts: stale when most recent transaction OR balance
        snapshot is more than _PLAID_STALE_DAYS days old.
      - Manual accounts: stale when no balance has been entered that
        covers the previous full calendar month.

    Returns a flat list of stale accounts so the model can name them
    instead of just saying "3 accounts are stale."
    """
    today = today or date.today()
    plaid_threshold = today - timedelta(days=_PLAID_STALE_DAYS)

    # Previous month start (manual cadence). Same logic as accounts.py.
    if today.month == 1:
        prev_month_start = date(today.year - 1, 12, 1)
    else:
        prev_month_start = date(today.year, today.month - 1, 1)
    prev_month_label = prev_month_start.strftime("%B")

    # MAX(date) per account in one query — the same N+1 dodge the
    # /stale endpoint uses.
    txn_max = dict(
        db.query(Transaction.account_id, func.max(Transaction.date))
        .group_by(Transaction.account_id)
        .all()
    )

    stale: list[dict] = []
    total_accounts = 0
    for acct in db.query(Account).all():
        total_accounts += 1
        as_of = acct.balance_as_of if acct.balance_as_of is not None else txn_max.get(acct.id)
        if as_of is None:
            continue  # never touched — skip rather than spam
        is_manual = acct.plaid_item_id is None
        days_stale = (today - as_of).days
        if is_manual:
            if as_of >= prev_month_start:
                continue
            reason = f"{prev_month_label} statement overdue"
        else:
            if as_of > plaid_threshold:
                continue
            reason = f"{days_stale} days since last sync"
        stale.append({
            "account": acct.custom_name or acct.name,
            "institution": acct.institution_name,
            "cadence": "manual" if is_manual else "plaid",
            "last_seen": as_of.isoformat(),
            "days_stale": days_stale,
            "reason": reason,
        })
    stale.sort(key=lambda x: x["days_stale"], reverse=True)
    return {
        "horizon_label": "right now",
        "total_accounts": total_accounts,
        "stale_count": len(stale),
        "stale_accounts": stale,
        "plaid_threshold_days": _PLAID_STALE_DAYS,
        "no_data": len(stale) == 0,
    }


# ─── Handler: savings_rate ─────────────────────────────────────────────

def _build_savings_rate_bundle(db: Session, horizon: str, *, today: Optional[date] = None) -> dict:
    """Bank-visible savings rate over the trailing 90 days, monthly avg.

    Mirrors the visible_savings_rate computation in
    /api/analytics/financial-pulse:

        monthly_inflow  = (sum of negative-amount, non-transfer txns over 90d) / 3
        monthly_outflow = (sum of positive-amount, non-transfer txns over 90d) / 3
        visible_rate    = (monthly_inflow - monthly_outflow) / monthly_inflow

    Caveat baked in: this is BANK-VISIBLE. 401(k) payroll deferrals are
    invisible to Plaid, so users with significant pre-tax retirement
    contributions will read low here vs reality.
    """
    today = today or date.today()
    last_90 = today - timedelta(days=90)

    inflow_90 = (
        db.query(func.coalesce(func.sum(-Transaction.amount), 0.0))
        .filter(
            Transaction.date >= last_90,
            Transaction.date <= today,
            Transaction.amount < 0,
            Transaction.is_transfer.is_(False),
        )
        .scalar()
        or 0.0
    )
    outflow_90 = (
        db.query(func.coalesce(func.sum(Transaction.amount), 0.0))
        .filter(
            Transaction.date >= last_90,
            Transaction.date <= today,
            Transaction.amount > 0,
            Transaction.is_transfer.is_(False),
        )
        .scalar()
        or 0.0
    )
    monthly_inflow = inflow_90 / 3.0
    monthly_outflow = outflow_90 / 3.0
    monthly_savings = monthly_inflow - monthly_outflow
    rate_pct = (
        round((monthly_savings / monthly_inflow) * 100, 1)
        if monthly_inflow > 0 else None
    )
    return {
        "horizon_label": "over the trailing 90 days",
        "window_start": last_90.isoformat(),
        "window_end": today.isoformat(),
        "monthly_inflow_dollars": round(monthly_inflow, 2),
        "monthly_outflow_dollars": round(monthly_outflow, 2),
        "monthly_savings_dollars": round(monthly_savings, 2),
        "visible_savings_rate_percent": rate_pct,
        "scope_note": (
            "This is the BANK-VISIBLE rate — 401(k) / 403(b) / 457 "
            "payroll deferrals never traverse a bank account, so they "
            "are NOT included. Users contributing significantly to "
            "pre-tax retirement plans will read lower here than their "
            "true savings rate."
        ),
        "no_data": monthly_inflow == 0,
    }


# ─── Registry + dispatch ───────────────────────────────────────────────

_HANDLERS: dict[str, Callable[[Session, str], dict]] = {
    "spending_total": _build_spending_total_bundle,
    "net_worth_change": _build_net_worth_change_bundle,
    "upcoming_bills": _build_upcoming_bills_bundle,
    "portfolio_status": _build_portfolio_status_bundle,
    "overspending": _build_overspending_bundle,
    "top_merchants": _build_top_merchants_bundle,
    "income_total": _build_income_total_bundle,
    "stale_accounts": _build_stale_accounts_bundle,
    "savings_rate": _build_savings_rate_bundle,
}


def known_prompt_ids() -> set[str]:
    return set(_HANDLERS.keys())


def known_horizon_ids(prompt_id: str) -> set[str]:
    for p in PROMPT_CATALOG:
        if p.id == prompt_id:
            return {h.id for h in p.horizons}
    return set()


def build_bundle(db: Session, prompt_id: str, horizon: str) -> dict:
    """Dispatch to the right handler. Raises KeyError on unknown id."""
    handler = _HANDLERS[prompt_id]
    return handler(db, horizon)


def build_user_prompt(prompt_id: str, horizon: str, bundle: dict) -> str:
    """Wrap the bundle in a per-prompt instruction.

    Each prompt gets a slightly different framing — bills wants a list-
    aware tone, net worth wants the directional move, etc. — but all
    share the hard rules in CHAT_SYSTEM_PROMPT.
    """
    framings = {
        "spending_total": (
            "The user asked: 'How much have I spent {label}?' "
            "Answer with the total dollars and, if useful, name the top "
            "category. If a comparison is provided, mention the direction "
            "of change vs the prior period."
        ),
        "net_worth_change": (
            "The user asked: 'What changed in my net worth {label}?' "
            "Lead with the current net worth, then the change vs the "
            "baseline snapshot. Mention dollars and percent if both are "
            "present."
        ),
        "upcoming_bills": (
            "The user asked: 'What bills are coming up {label}?' "
            "Lead with the count and total. If there are bills, name "
            "the largest one or the closest one by due date. If there "
            "are zero bills in the window, say so plainly."
        ),
        "portfolio_status": (
            "The user asked: 'How is my portfolio doing {label}?' "
            "Lead with total value and unrealized gain/loss if known. "
            "If a comparison exists, mention the change but include the "
            "caveat from the comparison.note field."
        ),
        "overspending": (
            "The user asked: 'Where am I overspending this month?' "
            "If no_data is true, just relay the reason. "
            "If nothing_to_flag is true, say all categories are on track "
            "for the month (mention day_into_month/days_in_month so the "
            "user knows it's still early). "
            "Otherwise lead with the count of categories over budget, "
            "name the worst one and how much it's over by, and mention "
            "any near-cap categories briefly."
        ),
        "top_merchants": (
            "The user asked: 'Who am I spending the most with {label}?' "
            "Lead with the top merchant and their total. List the next "
            "1-2 if useful. Mention share-of-total only if it's striking."
        ),
        "income_total": (
            "The user asked: 'How much income did I receive {label}?' "
            "Lead with the total dollars. Briefly include the scope_note "
            "caveat (payroll deferrals are NOT included) since users "
            "often forget Plaid can't see pre-tax 401(k) contributions."
        ),
        "stale_accounts": (
            "The user asked: 'Are any accounts overdue for an update?' "
            "If stale_count is 0, say so plainly in one sentence. "
            "Otherwise lead with the count, then name the worst 1-2 by "
            "days_stale, and mention whether they're Plaid-synced or "
            "manual (different fix paths)."
        ),
        "savings_rate": (
            "The user asked: 'What's my savings rate?' "
            "Lead with visible_savings_rate_percent. Briefly include the "
            "scope_note caveat about payroll deferrals being invisible "
            "to this calculation."
        ),
    }
    framing = framings.get(prompt_id, "Answer the user's question using the JSON.")
    framing = framing.format(label=bundle.get("horizon_label", "in the requested window"))
    return (
        f"{framing}\n\n"
        f"Pre-computed facts (use ONLY these numbers — do not invent any "
        f"other dollar figures or counts):\n"
        f"```json\n{json.dumps(bundle, indent=2)}\n```\n\n"
        f"Write the answer now."
    )


# ─── Demo answers ──────────────────────────────────────────────────────
#
# Same trick as DEMO_NARRATIVE in insights_narrative.py — short canned
# strings keyed by prompt_id so demo mode renders something useful even
# without Ollama installed. Numbers approximately match the seed data;
# update if the seed materially changes.
DEMO_ANSWERS: dict[str, dict[str, str]] = {
    "spending_total": {
        "today": "You've spent about $48 today across two transactions, mostly groceries.",
        "1w": "You've spent roughly $1,180 over the past 7 days, with Food & Dining the biggest category at $420.",
        "1mo": "Spending is around $4,287 over the past 30 days — about 8% below your prior 30-day pace.",
        "1yr": "Total spending over the past 12 months is about $52,400, with Housing and Food & Dining the two largest buckets.",
    },
    "net_worth_change": {
        "1d": "Your net worth is about $612,400 today, basically flat day-over-day.",
        "1w": "Net worth sits at about $612,400, up roughly $1,800 (+0.3%) over the past week.",
        "1mo": "Net worth is about $612,400, up roughly $7,200 (+1.2%) over the past month.",
        "1yr": "Net worth is about $612,400, up roughly $58,000 (+10.5%) over the past year.",
    },
    "upcoming_bills": {
        "7d": "Two bills are due in the next 7 days, totaling about $2,140 — mortgage on the 5th and a Chase card statement on the 7th.",
        "30d": "Five bills are due in the next 30 days, totaling about $4,860, with the mortgage being the largest at $2,012.",
    },
    "portfolio_status": {
        "today": "Your portfolio is worth about $284,300 today, with an unrealized gain of roughly $32,800 (+13%).",
        "1w": "Portfolio sits at about $284,300, an unrealized gain of about $32,800. Total assets are up roughly $2,100 over the past week.",
        "1mo": "Portfolio is at about $284,300 with an unrealized gain near $32,800; total assets are up roughly $5,400 over the past month.",
        "1yr": "Portfolio is around $284,300 with an unrealized gain of about $32,800. Total assets are up roughly $42,600 over the past year — note this is the change in total assets, not just investments.",
    },
    "overspending": {
        "now": "Two categories are over budget this month: Restaurants by $85 and Shopping by $40. Groceries is at 92% — close to the cap.",
    },
    "top_merchants": {
        "1w": "Whole Foods leads at $312 over the past 7 days, followed by Costco ($186) and Shell ($73).",
        "1mo": "Whole Foods is your top merchant at $1,240 over the past 30 days (about 11% of spending), then Costco ($720) and Amazon ($590).",
        "1yr": "Whole Foods leads the year at $14,200, followed by Costco ($8,300) and Amazon ($6,400).",
    },
    "income_total": {
        "1w": "About $2,800 in deposits hit your accounts over the past 7 days. Note this is bank-visible only — payroll deferrals aren't counted.",
        "1mo": "Roughly $11,600 in deposits over the past 30 days. Pre-tax retirement contributions don't traverse the bank, so this is a floor.",
        "1yr": "Around $138,400 in deposits over the past 12 months. Excludes 401(k) payroll deferrals, which Plaid can't see.",
    },
    "stale_accounts": {
        "now": "All accounts are up to date.",
    },
    "savings_rate": {
        "now": "Your bank-visible savings rate is about 22% over the past 90 days. Pre-tax 401(k) deferrals would push the true rate higher.",
    },
}


def demo_answer(prompt_id: str, horizon: str) -> Optional[str]:
    return DEMO_ANSWERS.get(prompt_id, {}).get(horizon)
